###################################
# Cluster Roles used by Prometheus
###################################
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  - nodes
  - nodes/proxy
  - nodes/metrics
  verbs: ["get", "list", "watch"]

- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]

- nonResourceURLs:
  - /metrics
  verbs:
  - get


###################################
# Cluster Role Binding Prometheus
###################################
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: monitoring



###################################
# Prometheus ServiceAccount
###################################
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring




###################################
# Deployment
###################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring

spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.1.0
        # run as root because of persistence volume storage
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 9090
          name: default
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        #- name: prometheus-data
        #  mountPath: /prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
      #- name: prometheus-data
      #  emptyDir: {}




