# Deployment
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bitwarden
  namespace: bitwarden
  labels:
    app: bitwarden
    name: bitwarden
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bitwarden
      name: bitwarden
  template:
    metadata:
      labels:
        app: bitwarden
        name: bitwarden
    spec:
      containers:
        - name: bitwarden
          image: vaultwarden/server
          env:
            - name: DOMAIN
              value: 'https://cloud.tnils.eu/bitwarden'
            - name: ROCKET_ADDRESS
              value: '0.0.0.0'
            - name: ROCKET_PORT
              value: '81'
          ports:
            - name: web
              containerPort: 81
          volumeMounts:
            - mountPath: /data
              name: bitwarden-data
      volumes:
      - name: bitwarden-data
        persistentVolumeClaim:
          claimName: bitwarden-pvc
