# Deployment
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: vaultwarden/server
          env:
            - name: DOMAIN
              value: 'https://vault.tnils.eu/'
            - name: ADMIN_TOKEN
              value: '$$argon2id$$v=19$$m=19456,t=2,p=1$$SHVYd3BjUVBSaDIvSjN6NDZhS2xyZGR1N2V1b0RLK1lQM1F0WEpxUUNBZz0$$yseTByAJMPNzoch8p7z0Kn3nkvi4qfOF9ILJhuOlHx0'
            - name: SIGNUPS_ALLOWED
              value: 'true'
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - mountPath: /data
              name: vault-data
      volumes:
      - name: vault-data
        persistentVolumeClaim:
          claimName: vault-pvc
