---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-pvc
  namespace: bitwarden
  annotations:
    volumeType: local
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: "distributed-pv"
