---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-pvc
  namespace: bitwarden
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: "distributed-pv"
