###############################
# Service
###############################
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
spec:
  ports:
    - name: web
      port: 81
      targetPort: web
  selector:
    app: vault

---
###################################################
# Ingress
###################################################
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: vault
  namespace: vault
  annotations:
    #traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  tls:
  - hosts:
      - cloud.tnils.eu
    secretName: tls-vault
  rules:
  - host: cloud.tnils.eu
    http:
      paths:
        - path: /vault
          pathType: Prefix
          backend:
            service:
              name: vault
              port:
                name: web
