###################################################
# Persistent Volumes
###################################################
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: distributed-pv
  labels:
  type: local
spec:
  storageClassName: manual
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/tobiasnils/data/distributed-storage/"