apiVersion: v1
kind: Service
metadata:
  name: firefly-iii-importer
  namespace: firefly-iii

spec:
  ports:
    - port: 8080
  selector:
    app: firefly-iii-importer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-iii-importer
  namespace: firefly-iii
  labels:
    app: firefly-iii-importer
spec:
  selector:
    matchLabels:
      app: firefly-iii-importer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: firefly-iii-importer
    spec:
      containers:
      - image: fireflyiii/data-importer:latest
        name: firefly-iii-importer
        env:
        - name: FF_DB_HOST
          value: firefly-iii-db
        - name: FF_DB_NAME
          value: "fireflyiii"
        - name: FF_DB_USERNAME
          value: "fireflyiii"
        - name: FF_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: firefly-iii-secrets
              key: db_password
        - name: FIREFLY_III_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: firefly-iii-secrets
              key: access_token
        - name: FIREFLY_III_URL
          value: "https://fin.tnils.eu/"
        - name: TRUSTED_PROXIES
          value: "**"
        ports:
        - containerPort: 8080
          name: firefly-iii
        imagePullPolicy: Always
