
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-upload-claim
  namespace: firefly-iii
  labels:
    app: firefly-iii
  annotations:
      volumeType: local
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-iii
  namespace: firefly-iii
  labels:
    app: firefly-iii
spec:
  selector:
    matchLabels:
      app: firefly-iii
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: firefly-iii
    spec:
      containers:
      - image: fireflyiii/core
        name: firefly-iii
        env:
        - name: APP_ENV
          value: "local"
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: firefly-iii-secrets
              key: app_key
        - name: DB_HOST
          value: firefly-iii-db
        - name: DB_CONNECTION
          value: pgsql
        - name: DB_DATABASE
          value: "fireflyiii"
        - name: DB_USERNAME
          value: "fireflyiii"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: firefly-iii-secrets
              key: db_password
        - name: TRUSTED_PROXIES
          value: "**"
        ports:
        - containerPort: 8080
          name: firefly-iii
        volumeMounts:
        - mountPath: "/var/www/html/storage/upload"
          name: firefly-iii-upload 
        imagePullPolicy: Always
      volumes:
        - name: firefly-iii-upload
          persistentVolumeClaim:
            claimName: firefly-iii-upload-claim
