# Service to expose Firefly III on an available port in Kubernetes cluster
# Assigned port can be seen with `kubectl get services firefly-iii`
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-iii
  namespace: firefly-iii
  
spec:
  ports:
    - port: 8080
      name: ui
      targetPort: ui
  selector:
    app: firefly-iii
    task: ui
    
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-iii-importer
  namespace: firefly-iii

spec:
  ports:
    - port: 8080
      name: import
      targetPort: import
  selector:
    app: firefly-iii
    task: importer

---
###################################################
# Ingress
###################################################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firefly-iii
  namespace: firefly-iii
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    #traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    traefik.ingress.kubernetes.io/rewrite-target: /
  
spec:
  tls:
    - hosts:
      - fin.tnils.eu
      secretName: tls-cluster
  rules:
  - host: fin.tnils.eu
    http:
      paths:
      - path: /accounting
        pathType: Prefix
        backend:
          service:
            name: firefly-iii
            port:
              name: ui
      - path: /import
        pathType: Prefix
        backend:
          service:
            name: firefly-iii-importer
            port:
              name: import
        


