# Service to expose Firefly III on an available port in Kubernetes cluster
# Assigned port can be seen with `kubectl get services firefly-iii`
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-iii
  namespace: firefly-iii
  labels:
    app: firefly-iii
spec:
  ports:
    - port: 8080
      name: firefly-iii
  selector:
    app: firefly-iii
    
---
###################################################
# Ingress
###################################################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firefly-iii
  namespace: firefly-iii
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  
spec:
  tls:
    - hosts:
      - fin.tnils.eu
      secretName: tls-cluster
  rules:
  - host: fin.tnils.eu
    http:
      paths:
      - path: /accounting
        pathType: Prefix
        backend:
          service:
            name: firefly-iii
            port:
              name: firefly-iii
        


