apiVersion: batch/v1
kind: CronJob
metadata:
  name: "firefly-iii-cron"
  namespace: firefly-iii
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      activeDeadlineSeconds: 120
      backoffLimit: 5
      template:
        metadata:
          labels:
            app: firefly-iii
        spec:
          containers:
            - name: cron
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
                - wget
              args:
                - "https://fin.tnils.eu/accounting/v1/cron/$(STATIC_CRON_TOKEN)"
              env:
                - name: STATIC_CRON_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: firefly-iii-secrets
                      key: static_cron_token
          restartPolicy: Never
