namespace: ingress-nginx
bases:
- github.com/kubernetes/ingress-nginx/deploy/static/provider/cloud?ref=controller-v0.44.0
# you can choose different versions here

patchesStrategicMerge:
- 020-service.yaml

resources:
- 030-cluster-issuer.yaml


