###############################
# Deplyoment Gitea
###############################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.20.3
          ports:
            - containerPort: 3000
              name: gitea
            - containerPort: 2222
              name: git-ssh
          env:
            - name: USER_UID
              value: '1000'
            - name: USER_GID
              value: '1000'
            - name: GITEA__cache__ENABLED
              value: 'true'
            - name: GITEA__cache__ADAPTER
              value: redis
            - name: GITEA__cache__HOST
              value: redis://localhost:6379/0?pool_size=100&idle_timeout=180s
            - name: GITEA__cache__TIEM_TTL
              value: 24h
            - name: GITEA__REPOSITORY__ENABLE_PUSH_CREATE_USER
              value: 'true'
            - name: GITEA__REPOSITORY__ENABLE_PUSH_CREATE_ORG
              value: 'true'
          volumeMounts:
          - mountPath: /data
            name: git-data

        - name: postgres
          image: docker.io/library/postgres:15
          env: 
          - name: POSTGRES_PASSWORD
            value: "tna"
          - name: POSTGRES_USER
            value: "tna"
          - name: PGDATA
            value: /data/pgdata
          volumeMounts:
          - mountPath: /data
            name: git-data

        - name: redis
          image: docker.io/library/redis:latest
          ports:
          - containerPort: 6379
          volumeMounts:
          - mountPath: /data
            name: git-data
      securityContext:
        fsGroup: 1000
      volumes:
        - name: git-data
          persistentVolumeClaim:
            claimName: git-pvc