apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: home
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: info@tnils.eu
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx