ingress:
  enabled: true
  annotations:
     cert-manager.io/issuer: letsencrypt-prod
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
  hosts:
    - host: git.tnils.eu
      paths:
        - path: /
          pathType: Prefix
  tls:
  - secretName: gitea-tls
    hosts:
        - git.tnils.eu
service:
  http:
    type: ClusterIP
    port: 3000
    clusterIP: None
  ssh:
    type: LoadBalancer
    port: 2222
    clusterIP: None

gitea:
  admin:
    existingSecret: gitea-admin-secret
    email: info@tnils.eu
  config:
    server:
      SSH_DOMAIN: gitea-ssh.example.com
    service:
      DISABLE_REGISTRATION: true
      SHOW_REGISTRATION_BUTTON: false
